"""auto_fix_schema

Revision ID: 0b685e2d74a2
Revises: force_rls_001
Create Date: 2026-04-24 09:00:18.357229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b685e2d74a2'
down_revision: Union[str, Sequence[str], None] = 'force_rls_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_codes',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_codes_email'), 'email_verification_codes', ['email'], unique=False)
    op.create_index(op.f('ix_email_verification_codes_id'), 'email_verification_codes', ['id'], unique=False)
    op.create_index(op.f('ix_email_verification_codes_is_deleted'), 'email_verification_codes', ['is_deleted'], unique=False)
    op.create_table('expenses',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('electricity', 'water', 'gas', 'cleaning', 'repair', 'elevator_maintenance', 'security', 'landscaping', 'insurance', 'property_tax', 'other', name='expensecategory'), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['property_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_agency_id'), 'expenses', ['agency_id'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_is_deleted'), 'expenses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_expenses_property_id'), 'expenses', ['property_id'], unique=False)
    op.create_index(op.f('ix_expenses_unit_id'), 'expenses', ['unit_id'], unique=False)
    op.add_column('agencies', sa.Column('address', sa.String(), nullable=True))
    op.alter_column('password_reset_attempts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_password_reset_attempts_id'), 'password_reset_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_attempts_is_deleted'), 'password_reset_attempts', ['is_deleted'], unique=False)
    op.add_column('properties', sa.Column('floor_count', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('year_built', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('land_area', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('commercial_type', sa.String(), nullable=True))
    op.add_column('property_units', sa.Column('area_sqm', sa.Integer(), nullable=True))
    op.add_column('property_units', sa.Column('unit_identifier', sa.String(), nullable=True))
    op.add_column('property_units', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('users', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.execute("DROP TYPE IF EXISTS userrole;")
    op.execute("CREATE TYPE userrole AS ENUM ('superadmin', 'boss', 'employee', 'tenant', 'landlord');")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::text::userrole;")
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.create_unique_constraint(None, 'users', ['firebase_uid'])
    op.create_foreign_key(None, 'users', 'agencies', ['agency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('superadmin', 'boss', 'employee', 'tenant', 'landlord', name='userrole'),
               type_=postgresql.ENUM('superadmin', 'standard', name='globaluserrole'),
               existing_nullable=False)
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'agency_id')
    op.drop_column('property_units', 'notes')
    op.drop_column('property_units', 'unit_identifier')
    op.drop_column('property_units', 'area_sqm')
    op.drop_column('properties', 'commercial_type')
    op.drop_column('properties', 'land_area')
    op.drop_column('properties', 'year_built')
    op.drop_column('properties', 'floor_count')
    op.drop_index(op.f('ix_password_reset_attempts_is_deleted'), table_name='password_reset_attempts')
    op.drop_index(op.f('ix_password_reset_attempts_id'), table_name='password_reset_attempts')
    op.alter_column('password_reset_attempts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('agencies', 'address')
    op.drop_index(op.f('ix_expenses_unit_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_property_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_is_deleted'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_agency_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_email_verification_codes_is_deleted'), table_name='email_verification_codes')
    op.drop_index(op.f('ix_email_verification_codes_id'), table_name='email_verification_codes')
    op.drop_index(op.f('ix_email_verification_codes_email'), table_name='email_verification_codes')
    op.drop_table('email_verification_codes')
    # ### end Alembic commands ###
