"""PRD schema compliance updates

Revision ID: 5130f4155e5b
Revises: f0a1b2c3d4e5
Create Date: 2026-04-14 18:51:02.776308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5130f4155e5b'
down_revision: Union[str, Sequence[str], None] = 'f0a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Önce enum type'ları oluştur (NOT NULL eklemeden önce)
    transaction_status_enum = sa.Enum('completed', 'pending_approval', 'partial', name='transactionstatus', create_type=False)
    transaction_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('building_operations_log', sa.Column('operation_date', sa.Date(), nullable=True))
    op.add_column('building_operations_log', sa.Column('transaction_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'building_operations_log', 'financial_transactions', ['transaction_id'], ['id'], ondelete='SET NULL')
    op.add_column('chat_conversations', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.add_column('chat_conversations', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.add_column('chat_conversations', sa.Column('archived_at', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('chat_messages', sa.Column('attachment_url', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('chat_messages', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('chat_messages', sa.Column('is_edited', sa.Boolean(), nullable=False))
    op.add_column('chat_messages', sa.Column('edited_at', sa.String(), nullable=True))
    op.alter_column('chat_messages', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_chat_messages_is_read'), 'chat_messages', ['is_read'], unique=False)
    op.drop_column('chat_messages', 'media_url')
    op.drop_column('chat_messages', 'message')

    # NOT NULL için önce nullable olarak ekle, sonra default ver
    op.add_column('financial_transactions', sa.Column('status', sa.Enum('completed', 'pending_approval', 'partial', name='transactionstatus', create_type=False), nullable=True))
    op.execute("UPDATE financial_transactions SET status = 'completed'")
    op.alter_column('financial_transactions', 'status', nullable=False)
    op.add_column('financial_transactions', sa.Column('ai_matched', sa.Boolean(), nullable=True))
    op.execute("UPDATE financial_transactions SET ai_matched = false")
    op.alter_column('financial_transactions', 'ai_matched', nullable=False)

    op.add_column('payment_schedules', sa.Column('transaction_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'payment_schedules', 'financial_transactions', ['transaction_id'], ['id'], ondelete='SET NULL')
    op.add_column('property_units', sa.Column('commission_rate', sa.Float(), nullable=True))
    op.add_column('property_units', sa.Column('youtube_video_link', sa.String(), nullable=True))
    op.add_column('property_units', sa.Column('media_links', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('property_units', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('contract_document_url', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('documents', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'documents')
    op.drop_column('tenants', 'contract_document_url')
    op.drop_column('property_units', 'features')
    op.drop_column('property_units', 'media_links')
    op.drop_column('property_units', 'youtube_video_link')
    op.drop_column('property_units', 'commission_rate')
    op.drop_constraint(None, 'payment_schedules', type_='foreignkey')
    op.drop_column('payment_schedules', 'transaction_id')
    op.drop_column('financial_transactions', 'ai_matched')
    op.alter_column('financial_transactions', 'status', nullable=True)
    op.execute("UPDATE financial_transactions SET status = NULL")
    op.drop_column('financial_transactions', 'status')
    op.add_column('chat_messages', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('media_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_chat_messages_is_read'), table_name='chat_messages')
    op.alter_column('chat_messages', 'deleted_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('chat_messages', 'edited_at')
    op.drop_column('chat_messages', 'is_edited')
    op.drop_column('chat_messages', 'deleted_by')
    op.drop_column('chat_messages', 'is_read')
    op.drop_column('chat_messages', 'attachment_url')
    op.drop_column('chat_messages', 'content')
    op.drop_column('chat_conversations', 'archived_at')
    op.drop_column('chat_conversations', 'is_archived')
    op.drop_column('chat_conversations', 'last_message_at')
    op.drop_constraint(None, 'building_operations_log', type_='foreignkey')
    op.drop_column('building_operations_log', 'transaction_id')
    op.drop_column('building_operations_log', 'operation_date')

    # Enum type'ı sil
    op.execute("DROP TYPE IF EXISTS transactionstatus")
    # ### end Alembic commands ###
