"""Init_DB

Revision ID: bd2426585749
Revises: 
Create Date: 2026-04-01 13:30:00.950033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd2426585749'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subscription_status', sa.Enum('trial', 'active', 'suspended', name='subscriptionstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agencies_id'), 'agencies', ['id'], unique=False)
    op.create_index(op.f('ix_agencies_is_deleted'), 'agencies', ['is_deleted'], unique=False)
    op.create_table('users',
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('superadmin', 'standard', name='globaluserrole'), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('agency_staff',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'agent', name='staffrole'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agency_staff_agency_id'), 'agency_staff', ['agency_id'], unique=False)
    op.create_index(op.f('ix_agency_staff_id'), 'agency_staff', ['id'], unique=False)
    op.create_index(op.f('ix_agency_staff_is_deleted'), 'agency_staff', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_agency_staff_user_id'), 'agency_staff', ['user_id'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('agent_user_id', sa.UUID(), nullable=False),
    sa.Column('client_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_agency_id'), 'chat_conversations', ['agency_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_agent_user_id'), 'chat_conversations', ['agent_user_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_client_user_id'), 'chat_conversations', ['client_user_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_id'), 'chat_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_is_deleted'), 'chat_conversations', ['is_deleted'], unique=False)
    op.create_table('invitations',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=False),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_agency_id'), 'invitations', ['agency_id'], unique=False)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_invitations_is_deleted'), 'invitations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_table('properties',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('building', 'single', name='propertytype'), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('central_dues', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_agency_id'), 'properties', ['agency_id'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_is_deleted'), 'properties', ['is_deleted'], unique=False)
    op.create_table('user_device_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fcm_token', sa.String(), nullable=False),
    sa.Column('device_type', sa.Enum('ios', 'android', 'web', name='devicetype'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcm_token')
    )
    op.create_index(op.f('ix_user_device_tokens_id'), 'user_device_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_device_tokens_is_deleted'), 'user_device_tokens', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_device_tokens_user_id'), 'user_device_tokens', ['user_id'], unique=False)
    op.create_table('building_operations_log',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('invoice_url', sa.String(), nullable=True),
    sa.Column('is_reflected_to_finance', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_operations_log_agency_id'), 'building_operations_log', ['agency_id'], unique=False)
    op.create_index(op.f('ix_building_operations_log_id'), 'building_operations_log', ['id'], unique=False)
    op.create_index(op.f('ix_building_operations_log_is_deleted'), 'building_operations_log', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_building_operations_log_property_id'), 'building_operations_log', ['property_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_is_deleted'), 'chat_messages', ['is_deleted'], unique=False)
    op.create_table('property_units',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('door_number', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('vacant', 'occupied', name='unitstatus'), nullable=False),
    sa.Column('vacant_since', sa.DateTime(), nullable=True),
    sa.Column('dues_amount', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_units_agency_id'), 'property_units', ['agency_id'], unique=False)
    op.create_index(op.f('ix_property_units_id'), 'property_units', ['id'], unique=False)
    op.create_index(op.f('ix_property_units_is_deleted'), 'property_units', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_property_units_property_id'), 'property_units', ['property_id'], unique=False)
    op.create_table('landlords_units',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('temp_name', sa.String(), nullable=True),
    sa.Column('temp_phone', sa.String(), nullable=True),
    sa.Column('ownership_share', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['property_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landlords_units_agency_id'), 'landlords_units', ['agency_id'], unique=False)
    op.create_index(op.f('ix_landlords_units_id'), 'landlords_units', ['id'], unique=False)
    op.create_index(op.f('ix_landlords_units_is_deleted'), 'landlords_units', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_landlords_units_unit_id'), 'landlords_units', ['unit_id'], unique=False)
    op.create_index(op.f('ix_landlords_units_user_id'), 'landlords_units', ['user_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('reporter_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='ticketpriority'), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='ticketstatus'), nullable=True),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['property_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_agency_id'), 'support_tickets', ['agency_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_id'), 'support_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_support_tickets_is_deleted'), 'support_tickets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_support_tickets_unit_id'), 'support_tickets', ['unit_id'], unique=False)
    op.create_table('tenants',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('temp_name', sa.String(), nullable=True),
    sa.Column('temp_phone', sa.String(), nullable=True),
    sa.Column('rent_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['property_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_agency_id'), 'tenants', ['agency_id'], unique=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_is_deleted'), 'tenants', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tenants_unit_id'), 'tenants', ['unit_id'], unique=False)
    op.create_index(op.f('ix_tenants_user_id'), 'tenants', ['user_id'], unique=False)
    op.create_table('financial_transactions',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('income', 'expense', name='transactiontype'), nullable=False),
    sa.Column('category', sa.Enum('rent', 'dues', 'utility', 'maintenance', 'commission', 'other', name='transactioncategory'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['property_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_transactions_agency_id'), 'financial_transactions', ['agency_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_id'), 'financial_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_is_deleted'), 'financial_transactions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_financial_transactions_property_id'), 'financial_transactions', ['property_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_tenant_id'), 'financial_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_unit_id'), 'financial_transactions', ['unit_id'], unique=False)
    op.create_table('payment_schedules',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paid_amount', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('rent', 'dues', 'utility', 'maintenance', 'commission', 'other', name='transactioncategory'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'partial', 'completed', name='paymentstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_schedules_agency_id'), 'payment_schedules', ['agency_id'], unique=False)
    op.create_index(op.f('ix_payment_schedules_id'), 'payment_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_payment_schedules_is_deleted'), 'payment_schedules', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payment_schedules_tenant_id'), 'payment_schedules', ['tenant_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messages_id'), 'ticket_messages', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_messages_is_deleted'), 'ticket_messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_is_deleted'), table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_payment_schedules_tenant_id'), table_name='payment_schedules')
    op.drop_index(op.f('ix_payment_schedules_is_deleted'), table_name='payment_schedules')
    op.drop_index(op.f('ix_payment_schedules_id'), table_name='payment_schedules')
    op.drop_index(op.f('ix_payment_schedules_agency_id'), table_name='payment_schedules')
    op.drop_table('payment_schedules')
    op.drop_index(op.f('ix_financial_transactions_unit_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_tenant_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_property_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_is_deleted'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_agency_id'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    op.drop_index(op.f('ix_tenants_user_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_unit_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_is_deleted'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_agency_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_support_tickets_unit_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_is_deleted'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_agency_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_landlords_units_user_id'), table_name='landlords_units')
    op.drop_index(op.f('ix_landlords_units_unit_id'), table_name='landlords_units')
    op.drop_index(op.f('ix_landlords_units_is_deleted'), table_name='landlords_units')
    op.drop_index(op.f('ix_landlords_units_id'), table_name='landlords_units')
    op.drop_index(op.f('ix_landlords_units_agency_id'), table_name='landlords_units')
    op.drop_table('landlords_units')
    op.drop_index(op.f('ix_property_units_property_id'), table_name='property_units')
    op.drop_index(op.f('ix_property_units_is_deleted'), table_name='property_units')
    op.drop_index(op.f('ix_property_units_id'), table_name='property_units')
    op.drop_index(op.f('ix_property_units_agency_id'), table_name='property_units')
    op.drop_table('property_units')
    op.drop_index(op.f('ix_chat_messages_is_deleted'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_building_operations_log_property_id'), table_name='building_operations_log')
    op.drop_index(op.f('ix_building_operations_log_is_deleted'), table_name='building_operations_log')
    op.drop_index(op.f('ix_building_operations_log_id'), table_name='building_operations_log')
    op.drop_index(op.f('ix_building_operations_log_agency_id'), table_name='building_operations_log')
    op.drop_table('building_operations_log')
    op.drop_index(op.f('ix_user_device_tokens_user_id'), table_name='user_device_tokens')
    op.drop_index(op.f('ix_user_device_tokens_is_deleted'), table_name='user_device_tokens')
    op.drop_index(op.f('ix_user_device_tokens_id'), table_name='user_device_tokens')
    op.drop_table('user_device_tokens')
    op.drop_index(op.f('ix_properties_is_deleted'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_agency_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_is_deleted'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_agency_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_chat_conversations_is_deleted'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_client_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_agent_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_agency_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_agency_staff_user_id'), table_name='agency_staff')
    op.drop_index(op.f('ix_agency_staff_is_deleted'), table_name='agency_staff')
    op.drop_index(op.f('ix_agency_staff_id'), table_name='agency_staff')
    op.drop_index(op.f('ix_agency_staff_agency_id'), table_name='agency_staff')
    op.drop_table('agency_staff')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_agencies_is_deleted'), table_name='agencies')
    op.drop_index(op.f('ix_agencies_id'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
