"""add_rent_price_to_property_units

Revision ID: cb799e57102f
Revises: bd2426585749
Create Date: 2026-04-10 21:34:13.268738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb799e57102f'
down_revision: Union[str, Sequence[str], None] = 'bd2426585749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_units', sa.Column('rent_price', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('status', sa.Enum('active', 'expired', 'terminated', name='contractstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'status')
    op.drop_column('property_units', 'rent_price')
    # ### end Alembic commands ###
